# Указываем версию Docker Compose
version: '3.11'

# Определяем сервисы (в нашем случае один - веб-приложение)
services:
  web:
    # Собирать образ из Dockerfile в текущей директории
    build: .
    # Название для собранного образа
    image: quiz-project-web
    # Пробрасываем порт 5000 с хоста в контейнер
    ports:
      - "5000:5000"
    # Настраиваем тома (volumes) для сохранения данных
    volumes:
      # Связываем папку с кодом на хосте с папкой в контейнере.
      # Это позволяет вносить изменения в код без пересборки образа.
      - ./quiz_project:/app
      # Создаем именованный том для хранения файла базы данных SQLite.
      # Это гарантирует, что данные не потеряются при перезапуске контейнера.
      - db_volume:/app/instance
    # Переменные окружения для контейнера
    environment:
      - FLASK_ENV=development

# Определяем именованные тома
volumes:
  # Том для хранения базы данных
  db_volume: 