"""Add groups column to tests table

Revision ID: cd3d938b6d44
Revises: 1ac98918f436
Create Date: 2025-07-16 00:03:34.493478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3d938b6d44'
down_revision = '1ac98918f436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups', sa.Text(), nullable=True))
        batch_op.drop_column('test_groups')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_groups', sa.TEXT(), nullable=True))
        batch_op.drop_column('groups')

    # ### end Alembic commands ###
